env:
  global:
    - CC_TEST_REPORTER_ID=00a50e18e14874b0d86236c35828be7c01d9ff917215608666b4ffd8cfa1b573
addons:
  postgresql: 9.6
bundler_args: --jobs 4 --retry 3
cache: bundler
language: ruby
notifications:
  email: false
rvm:
  - 2.3.5
  - 2.4.2
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - bundle exec rails db:setup
script:
  - bundle exec rails bundle:audit
  - bundle exec license_finder --quiet
  - bundle exec rubocop
  - bundle exec rails test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
sudo: false
