version: '3'

services:
  #  db:
  #    image: mysql:5.7
  #    volumes:
  #      - ./db_data:/var/lib/mysql
  #    ports:
  #      - "3309:3306"
  #    restart: always
  #    environment:
  #      MYSQL_ROOT_PASSWORD: develdevel
  #      MYSQL_DATABASE: devel
  #      MYSQL_USER: devel
  #      MYSQL_PASSWORD: devel

   rails:
    #  depends_on:
    #    - db
     image: renocollective/rails
     volumes:
       - ./:/var/www/app
     ports:
       - "3000:3000"
     restart: always
    #  environment:

volumes:
    db_data:
